extends Node

signal level_upped(level_attribute_points)
signal attributes_changed(new_attributes)

signal post_current_status(current_character_status)
signal post_current_attributes(current_character_attributes)
